<a href="https://colab.research.google.com/github/gauritiwari08-sudo/Data-Analyst-Portfolio/blob/main/Python/Numpy_prog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [1]:
import numpy as np
array=np.array([[['a','b'],['c','d']],
                [['e','f'],['g','h']],
                [['i','j'],['k','l']]])
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)
print(array[0][0][0])
print(array[1][1][0])
print(array[0][0][1] + array[2][0][1])

(3, 2, 2)
3
12
<U1
a
g
bj


In [2]:
#reshaping array
print(array.reshape(2,-1))

[['a' 'b' 'c' 'd' 'e' 'f']
 ['g' 'h' 'i' 'j' 'k' 'l']]


In [3]:
print(array.flatten())

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']


In [4]:
print(array.ravel())

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']


In [6]:
print(array)

[[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]

 [['i' 'j']
  ['k' 'l']]]


In [9]:
#broadcasting
array1=np.array([[2,3,4],[5,6,7]])
array2=np.array([[6,7,6],[1,8,9]])
print(array1*array2)

[[12 21 24]
 [ 5 48 63]]


In [15]:
#Transpose of matrix
print(array)
print(array.T)
print(array.transpose())
print(np.transpose(array))

[[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]

 [['i' 'j']
  ['k' 'l']]]
[[['a' 'e' 'i']
  ['c' 'g' 'k']]

 [['b' 'f' 'j']
  ['d' 'h' 'l']]]
[[['a' 'e' 'i']
  ['c' 'g' 'k']]

 [['b' 'f' 'j']
  ['d' 'h' 'l']]]
[[['a' 'e' 'i']
  ['c' 'g' 'k']]

 [['b' 'f' 'j']
  ['d' 'h' 'l']]]


In [21]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

arr3=np.concatenate((arr1,arr2))
print(arr3)



[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


In [22]:
# @title AI prompt cell

import ipywidgets as widgets
from IPython.display import display, HTML, Markdown,clear_output
from google.colab import ai

dropdown = widgets.Dropdown(
    options=[],
    layout={'width': 'auto'}
)

def update_model_list(new_options):
    dropdown.options = new_options
update_model_list(ai.list_models())

text_input = widgets.Textarea(
    placeholder='Ask me anything....',
    layout={'width': 'auto', 'height': '100px'},
)

button = widgets.Button(
    description='Submit Text',
    disabled=False,
    tooltip='Click to submit the text',
    icon='check'
)

output_area = widgets.Output(
     layout={'width': 'auto', 'max_height': '300px','overflow_y': 'scroll'}
)

def on_button_clicked(b):
    with output_area:
        output_area.clear_output(wait=False)
        accumulated_content = ""
        for new_chunk in ai.generate_text(prompt=text_input.value, model_name=dropdown.value, stream=True):
            if new_chunk is None:
                continue
            accumulated_content += new_chunk
            clear_output(wait=True)
            display(Markdown(accumulated_content))

button.on_click(on_button_clicked)
vbox = widgets.GridBox([dropdown, text_input, button, output_area])

display(HTML("""
<style>
.widget-dropdown select {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
.widget-textarea textarea {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
</style>
"""))
display(vbox)


GridBox(children=(Dropdown(layout=Layout(width='auto'), options=('google/gemini-3.5-flash',), value='google/ge…